spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: user-service
          uri: http://localhost:9098
          predicates:
            - Path=/users/**
        - id: product-service
          uri: http://localhost:9099
          predicates:
            - Path=/products/**


server:
  port: 8094

