spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 9098

kafka:
  consumer:
    group:
      id: userGroup
  topics:
    productCartAddition: productCartAddition
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

